apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.wordpress.name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.wordpress.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.wordpress.name }}
    spec:
      containers:
        - name: {{ .Values.wordpress.name }}
          image: {{ .Values.wordpress.image }}
          ports:
            - containerPort: {{ .Values.wordpress.port }}
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.wordpress.host}}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.wordpress.db }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.wordpress.user }}
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.wordpress.name }}-secret
                  key: db-password