apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wordpress.name }}-service
spec:
  selector:
    app: {{ .Values.wordpress.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.wordpress.port }}
      targetPort: {{ .Values.wordpress.port }}
  type: LoadBalancer